version: '3'
services:
  web:
    container_name: ghibli-style-shader
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: ['pnpm', 'start']
